name: tb_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_debounce: ^2.0.3
  google_fonts: ^6.2.1
  provider: ^6.1.5
  flutter_map: ^8.2.1
  http: ^1.2.0
  google_maps_flutter: ^2.10.1
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  geocoding: ^4.0.0
  table_calendar: ^3.0.9 
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  characters: ^1.2.0
  image_picker: ^1.1.2 
  flutter_dotenv: ^6.0.0
  dio: ^5.4.0
  youtube_player_flutter: ^9.1.2
  pdfx: ^2.6.0
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.1
  video_player: ^2.9.2
  jitsi_meet_flutter_sdk: ^10.2.0
  google_generative_ai: ^0.2.2
  mailer: ^6.5.0
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/tbisita_logo.png
    - assets/images/tbisita_logo1.png
    - assets/images/tbisita_logo2.png
    - assets/images/doc1.png
    - assets/images/doc2.png
    - assets/images/doc3.png
    - assets/images/map1.png
    - assets/images/guidelines.png
    - assets/documents/NTP_MOP_6TH_EDITION.pdf
    - assets/videos/tbdots.mp4
    - .env
    - assets/images/splash1.png
    - assets/images/splash2.png
    - assets/images/splash3.png
    - assets/images/splash4.png
    - assets/images/logo1.png