// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzlZVPAPDMlWKtOgUs2lzt0X_5f8GerU',
    appId: '1:60521531518:web:a16dfdf727fa4d570c302f',
    messagingSenderId: '60521531518',
    projectId: 'registration-form-472dc',
    authDomain: 'registration-form-472dc.firebaseapp.com',
    storageBucket: 'registration-form-472dc.firebasestorage.app',
    measurementId: 'G-3QMWXN5PBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfI6ne52qKZFzsyXbGbUm67sGucH-U4Ac',
    appId: '1:60521531518:android:7c62e786c916afcd0c302f',
    messagingSenderId: '60521531518',
    projectId: 'registration-form-472dc',
    storageBucket: 'registration-form-472dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMPw5u0bdwvgyaYoQXACD3opOmXigsOU',
    appId: '1:60521531518:ios:b7996ec8c8b134ac0c302f',
    messagingSenderId: '60521531518',
    projectId: 'registration-form-472dc',
    storageBucket: 'registration-form-472dc.firebasestorage.app',
    iosBundleId: 'com.example.tbFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMPw5u0bdwvgyaYoQXACD3opOmXigsOU',
    appId: '1:60521531518:ios:b7996ec8c8b134ac0c302f',
    messagingSenderId: '60521531518',
    projectId: 'registration-form-472dc',
    storageBucket: 'registration-form-472dc.firebasestorage.app',
    iosBundleId: 'com.example.tbFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDzlZVPAPDMlWKtOgUs2lzt0X_5f8GerU',
    appId: '1:60521531518:web:af1ca53346363c830c302f',
    messagingSenderId: '60521531518',
    projectId: 'registration-form-472dc',
    authDomain: 'registration-form-472dc.firebaseapp.com',
    storageBucket: 'registration-form-472dc.firebasestorage.app',
    measurementId: 'G-FDP7QCXBXM',
  );
}
